import Image from "next/image";
import { Reveal, SectionHeading, Panel } from "./shared";

const FIGURES = [
  {
    src: "/figures/fig_demand_vs_reservation.png",
    w: 1650,
    h: 600,
    title: "Reservation tracks uncertain demand",
    cap: "UCRA reservation (red) rides the diurnal demand cycle (blue) — above realized demand in every one of the 252 slots, far below flat static-peak provisioning.",
  },
  {
    src: "/figures/fig_quantile_band.png",
    w: 1650,
    h: 600,
    title: "Stage 1: the quantile band",
    cap: "q05–q99 predictive band from the quantile LSTM vs realized demand. The 90% central band covers 96.0% of test slots.",
  },
  {
    src: "/figures/fig_drift_demo.png",
    w: 1650,
    h: 1050,
    title: "Stage 5: surge, trigger, recover",
    cap: "The drift-demo experiment behind the interactive section: +35% surge at slot 37, frozen agent keeps violating while the self-evolving agent fine-tunes and recovers.",
  },
  {
    src: "/figures/fig_cttc_slices.png",
    w: 1800,
    h: 630,
    title: "CTTC: violations & over-provisioning",
    cap: "Per-slice comparison of operator, static q90 and UCRA on the public CTTC snapshots.",
  },
];

export function Gallery() {
  return (
    <section className="relative py-20 sm:py-28">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <SectionHeading
          kicker="From the repo"
          title="Figures generated by make_figures.py"
          sub="Straight out of outputs/ — the same plots a reviewer gets when re-running the pipeline."
        />
        <div className="mt-12 grid gap-5 md:grid-cols-2">
          {FIGURES.map((f, i) => (
            <Reveal key={f.src} delay={(i % 2) * 0.08}>
              <Panel className="overflow-hidden">
                <figure>
                  <div className="bg-zinc-100 p-3">
                    <Image
                      src={f.src}
                      alt={f.title}
                      width={f.w}
                      height={f.h}
                      className="h-auto w-full rounded-lg"
                      sizes="(max-width: 768px) 100vw, 560px"
                    />
                  </div>
                  <figcaption className="px-5 py-4">
                    <p className="text-sm font-semibold text-zinc-100">
                      {f.title}
                    </p>
                    <p className="mt-1 text-xs leading-relaxed text-zinc-500">
                      {f.cap}
                    </p>
                  </figcaption>
                </figure>
              </Panel>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}
